# THREAD VARS
MUSIC_IN_ACTION = None
MUSIC_OUT_ACCPATTERN = 0
MUSIC_OUT_ROW = 0
MUSIC_OUT_PULSE = 0

# SHARED VARS
GFX=None
DISPLAY=None
DISTANCE_START = -10
DISTANCE_CLOSE = -1.3
DISTANCE_FAR = -10
SPRITES=None
SPR_PIRATE=None